# Generated by Django 6.0.2 on 2026-02-25 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_quick_responder",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="is_top_rated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="users",
            name="role",
            field=models.CharField(
                choices=[("student", "Student"), ("landlord", "Landlord")],
                default="student",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="LandlordProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("national_id", models.CharField(blank=True, max_length=50, null=True)),
                ("is_id_verified", models.BooleanField(default=False)),
                (
                    "total_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landlord_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("university", models.CharField(blank=True, max_length=255, null=True)),
                ("faculty", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "year_of_study",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("languages", models.JSONField(blank=True, default=list)),
                ("profile_strength", models.IntegerField(default=0)),
                ("is_looking_for_room", models.BooleanField(default=False)),
                ("lifestyle_tags", models.JSONField(blank=True, default=list)),
                (
                    "sleeping_time",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("early", "Early (9-10 PM)"),
                            ("normal", "Normal (11 PM)"),
                            ("late", "Late (12+ AM)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "study_environment",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "music_preference",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "guests_policy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("never", "Never"),
                            ("sometimes", "Sometimes"),
                            ("often", "Often"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "personality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quiet", "Quiet"),
                            ("social", "Social"),
                            ("moderate", "Moderate"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cleanliness",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "smoking",
                    models.CharField(
                        blank=True,
                        choices=[("smoker", "Smoker"), ("non_smoker", "Non-Smoker")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("budget_min", models.IntegerField(default=0)),
                ("budget_max", models.IntegerField(default=0)),
                (
                    "room_type_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("shared", "Shared"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "preferred_room_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("single", "Single"),
                            ("shared", "Shared"),
                            ("both", "Both"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "smoking_preference",
                    models.CharField(
                        blank=True,
                        choices=[("smoker", "Smoker"), ("non_smoker", "Non-Smoker")],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "sleep_schedule_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("early", "Early (9-10 PM)"),
                            ("normal", "Normal (11 PM)"),
                            ("late", "Late (12+ AM)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cleanliness_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "personality_pref",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("quiet", "Quiet"),
                            ("social", "Social"),
                            ("moderate", "Moderate"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VerificationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("student_id", "Student ID"),
                            ("university_email", "University Email"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="verifications/"),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
