# Generated by Django 6.0.5 on 2026-06-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_unit",
            field=models.CharField(
                choices=[
                    ("whole", "Whole Property"),
                    ("room", "By Room"),
                    ("bed", "By Bed"),
                ],
                default="whole",
                max_length=10,
            ),
        ),
    ]
