# Generated by Django 6.0.5 on 2026-06-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_stripe_marketplace_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="remaining_amount_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booking",
            name="remaining_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="remaining_payment_requested",
            field=models.BooleanField(default=False),
        ),
    ]
