# Generated by Django 6.0.2 on 2026-03-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="gender_preference",
            field=models.CharField(
                choices=[("male", "Males Only"), ("female", "Females Only")],
                max_length=10,
            ),
        ),
    ]
