# Generated by Django 6.0.5 on 2026-06-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_add_room_bed_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="available_from",
            field=models.DateField(
                blank=True,
                help_text="Date property becomes available. Null = available now.",
                null=True,
            ),
        ),
    ]
