# Generated by Django 6.0.5 on 2026-06-11 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                help_text="Links property review to a specific booking. Null for user-to-user reviews.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="bookings.booking",
            ),
        ),
    ]
