# Generated by Django 6.0.5 on 2026-06-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_post_title_postvote_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
